<?php

namespace App\Http\Controllers;

use App\Models\PurchaseInvoice;
use App\Models\PurchaseInvoiceItem;
use App\Models\Product;
use App\Models\MeasurementUnit;
use App\Models\ChartOfAccounts;
use App\Models\Voucher;
use App\Traits\PostsAccountingEntries;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;

class PurchaseInvoiceController extends Controller
{
    use PostsAccountingEntries;

    public function index()
    {
        $invoices = PurchaseInvoice::with('vendor')->latest()->get();
        return view('purchases.index', compact('invoices'));
    }

    public function create()
    {
        $products = Product::get();
        $vendors  = ChartOfAccounts::where('account_type', 'vendor')->get();
        $units    = MeasurementUnit::all();
        return view('purchases.create', compact('products', 'vendors', 'units'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'invoice_date'         => 'required|date',
            'vendor_id'            => 'required|exists:chart_of_accounts,id',
            'payment_terms'        => 'nullable|string',
            'bill_no'              => 'nullable|string|max:100',
            'ref_no'               => 'nullable|string|max:100',
            'remarks'              => 'nullable|string',
            'attachments.*'        => 'nullable|file|mimes:jpg,jpeg,png,pdf,zip|max:2048',
            'items.*.item_id'      => 'required|exists:products,id',
            'items.*.variation_id' => 'nullable|exists:product_variations,id',
            'items.*.quantity'     => 'required|numeric|min:0.01',
            'items.*.unit'         => 'required|exists:measurement_units,id',
            'items.*.price'        => 'required|numeric|min:0',
            'items.*.item_remarks' => 'nullable|string',
            'convance_charges'     => 'nullable|numeric|min:0',
            'labour_charges'       => 'nullable|numeric|min:0',
            'bill_discount'        => 'nullable|numeric|min:0',
        ]);

        DB::beginTransaction();
        try {
            // invoice_no is auto-generated by the model's booted() hook
            $invoice = PurchaseInvoice::create([
                'vendor_id'        => $request->vendor_id,
                'invoice_date'     => $request->invoice_date,
                'payment_terms'    => $request->payment_terms,
                'bill_no'          => $request->bill_no,
                'ref_no'           => $request->ref_no,
                'remarks'          => $request->remarks,
                'convance_charges' => $request->convance_charges ?? 0,
                'labour_charges'   => $request->labour_charges   ?? 0,
                'bill_discount'    => $request->bill_discount    ?? 0,
                'created_by'       => auth()->id(),
            ]);

            $this->saveItems($invoice, $request->items ?? []);
            $this->saveAttachments($invoice, $request);

            $invoice->loadMissing('items');
            $this->postPurchaseEntries($invoice);

            DB::commit();
            Log::info('[Purchase] Invoice created', [
                'id'         => $invoice->id,
                'invoice_no' => $invoice->invoice_no,
            ]);
            return redirect()->route('purchase_invoices.index')
                ->with('success', 'Purchase Invoice ' . $invoice->invoice_no . ' created successfully.');

        } catch (\Throwable $e) {
            DB::rollBack();
            Log::error('[Purchase] Store failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            return back()->withInput()->with('error', 'Failed to create invoice: ' . $e->getMessage());
        }
    }

    public function edit($id)
    {
        $invoice  = PurchaseInvoice::with(['items', 'attachments'])->findOrFail($id);
        $vendors  = ChartOfAccounts::where('account_type', 'vendor')->get();
        $products = Product::select('id', 'name', 'barcode', 'measurement_unit')->get();
        $units    = MeasurementUnit::all();
        return view('purchases.edit', compact('invoice', 'vendors', 'products', 'units'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'invoice_date'         => 'required|date',
            'vendor_id'            => 'required|exists:chart_of_accounts,id',
            'payment_terms'        => 'nullable|string',
            'bill_no'              => 'nullable|string|max:100',
            'ref_no'               => 'nullable|string|max:100',
            'remarks'              => 'nullable|string',
            'attachments.*'        => 'nullable|file|mimes:jpg,jpeg,png,pdf,zip|max:2048',
            'items.*.item_id'      => 'required|exists:products,id',
            'items.*.variation_id' => 'nullable|exists:product_variations,id',
            'items.*.quantity'     => 'required|numeric|min:0.01',
            'items.*.unit'         => 'required|exists:measurement_units,id',
            'items.*.price'        => 'required|numeric|min:0',
            'items.*.item_remarks' => 'nullable|string',
            'convance_charges'     => 'nullable|numeric|min:0',
            'labour_charges'       => 'nullable|numeric|min:0',
            'bill_discount'        => 'nullable|numeric|min:0',
        ]);

        DB::beginTransaction();
        try {
            $invoice = PurchaseInvoice::findOrFail($id);
            $invoice->update([
                // invoice_no is never changed on update
                'vendor_id'        => $request->vendor_id,
                'invoice_date'     => $request->invoice_date,
                'payment_terms'    => $request->payment_terms,
                'bill_no'          => $request->bill_no,
                'ref_no'           => $request->ref_no,
                'remarks'          => $request->remarks,
                'convance_charges' => $request->convance_charges ?? 0,
                'labour_charges'   => $request->labour_charges   ?? 0,
                'bill_discount'    => $request->bill_discount    ?? 0,
            ]);

            $invoice->items()->delete();
            $this->saveItems($invoice, $request->items ?? []);
            $this->saveAttachments($invoice, $request);

            $invoice->loadMissing('items');
            $this->postPurchaseEntries($invoice);

            DB::commit();
            Log::info('[Purchase] Invoice updated', [
                'id'         => $invoice->id,
                'invoice_no' => $invoice->invoice_no,
            ]);
            return redirect()->route('purchase_invoices.index')
                ->with('success', 'Purchase Invoice ' . $invoice->invoice_no . ' updated successfully.');

        } catch (\Throwable $e) {
            DB::rollBack();
            Log::error('[Purchase] Update failed', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);
            return back()->withInput()->with('error', 'Failed to update invoice: ' . $e->getMessage());
        }
    }

    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            $invoice = PurchaseInvoice::with('attachments')->findOrFail($id);
            $this->deleteVoucherEntries($invoice);
            foreach ($invoice->attachments as $attachment) {
                Storage::disk('public')->delete($attachment->file_path);
            }
            $invoice->delete();
            DB::commit();
            return redirect()->route('purchase_invoices.index')
                ->with('success', 'Purchase Invoice ' . $invoice->invoice_no . ' deleted successfully.');

        } catch (\Throwable $e) {
            DB::rollBack();
            Log::error('[Purchase] Destroy failed', [
                'id'    => $id,
                'error' => $e->getMessage(),
            ]);
            return back()->with('error', 'Failed to delete invoice.');
        }
    }

    public function print($id)
    {
        $invoice = PurchaseInvoice::with([
            'vendor',
            'items.product',
            'items.variation',
            'items.measurementUnit',
        ])->findOrFail($id);

        $pdf = new \TCPDF();
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        $pdf->SetCreator('Jild');
        $pdf->SetAuthor('Jild');
        $pdf->SetTitle('Purchase Invoice ' . $invoice->invoice_no);
        $pdf->SetMargins(10, 10, 10);
        $pdf->AddPage();
        $pdf->setCellPadding(1.5);

        $logoPath = public_path('assets/img/Jild-Logo.png');
        if (file_exists($logoPath)) {
            $pdf->Image($logoPath, 10, 10, 30);
        }

        // Info box — uses invoice_no instead of id
        $pdf->SetXY(130, 12);
        $pdf->writeHTML('
            <table border="1" cellpadding="4" style="font-size:10px;line-height:14px;border-collapse:collapse;">
                <tr><td><b>Invoice #</b></td><td>' . $invoice->invoice_no . '</td></tr>
                <tr><td><b>Date</b></td><td>' . Carbon::parse($invoice->invoice_date)->format('d/m/Y') . '</td></tr>
                <tr><td><b>Bill No</b></td><td>' . ($invoice->bill_no ?? '-') . '</td></tr>
                <tr><td><b>Vendor</b></td><td>' . ($invoice->vendor->name ?? '-') . '</td></tr>
            </table>',
        false, false, false, false, '');

        $pdf->Line(60, 52.25, 200, 52.25);
        $pdf->SetXY(10, 48);
        $pdf->SetFillColor(23, 54, 93);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('helvetica', '', 12);
        $pdf->Cell(50, 8, 'Purchase Invoice', 0, 1, 'C', 1);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->Ln(5);

        $html        = '<table border="0.3" cellpadding="4" style="text-align:center;font-size:10px;">
            <tr style="background-color:#f5f5f5;font-weight:bold;">
                <th width="7%">S.No</th>
                <th width="20%">Item Name</th>
                <th width="28%">Variation</th>
                <th width="18%">Qty</th>
                <th width="12%">Rate</th>
                <th width="15%">Total</th>
            </tr>';

        $count = 0; $totalAmount = 0;

        foreach ($invoice->items as $item) {
            $count++;
            $amount       = $item->quantity * $item->price;
            $totalAmount += $amount;
            $html .= '
            <tr>
                <td>' . $count . '</td>
                <td>' . ($item->product->name ?? '-') . '</td>
                <td>' . ($item->variation->sku ?? '-') . '</td>
                <td>' . number_format($item->quantity, 2) . ' ' . ($item->measurementUnit->shortcode ?? '') . '</td>
                <td align="right">' . number_format($item->price, 2) . '</td>
                <td align="right">' . number_format($amount, 2) . '</td>
            </tr>';
        }

        $html .= '<tr><td colspan="5" align="right"><b>Sub Total</b></td>'
            . '<td align="right"><b>' . number_format($totalAmount, 2) . '</b></td></tr>';

        if ($invoice->convance_charges > 0) {
            $totalAmount += $invoice->convance_charges;
            $html .= '<tr><td colspan="5" align="right">Conveyance</td>'
                . '<td align="right">' . number_format($invoice->convance_charges, 2) . '</td></tr>';
        }
        if ($invoice->labour_charges > 0) {
            $totalAmount += $invoice->labour_charges;
            $html .= '<tr><td colspan="5" align="right">Labour</td>'
                . '<td align="right">' . number_format($invoice->labour_charges, 2) . '</td></tr>';
        }
        if ($invoice->bill_discount > 0) {
            $totalAmount -= $invoice->bill_discount;
            $html .= '<tr><td colspan="5" align="right">Discount</td>'
                . '<td align="right">(' . number_format($invoice->bill_discount, 2) . ')</td></tr>';
        }

        $html .= '<tr style="background-color:#f5f5f5;">'
            . '<td colspan="5" align="right"><b>Net Total</b></td>'
            . '<td align="right"><b>' . number_format($totalAmount, 2) . '</b></td>'
            . '</tr></table>';

        $pdf->writeHTML($html, true, false, true, false, '');

        if (!empty($invoice->remarks)) {
            $pdf->writeHTML(
                '<b>Remarks:</b><br><span style="font-size:12px;">' . nl2br($invoice->remarks) . '</span>',
                true, false, true, false, ''
            );
        }

        $pdf->Ln(20);
        $y = $pdf->GetY();
        $pdf->Line(28, $y, 68, $y);
        $pdf->Line(130, $y, 170, $y);
        $pdf->SetXY(28,  $y + 2); $pdf->Cell(40, 6, 'Received By',   0, 0, 'C');
        $pdf->SetXY(130, $y + 2); $pdf->Cell(40, 6, 'Authorized By', 0, 0, 'C');

        return $pdf->Output('purchase_invoice_' . $invoice->invoice_no . '.pdf', 'I');
    }

    // ── API / Helper endpoints ────────────────────────────────────────

    public function getInvoicesByItem($itemId)
    {
        $invoices = PurchaseInvoice::whereHas('items', fn($q) => $q->where('item_id', $itemId))
            ->with('vendor')
            ->get(['id', 'invoice_no', 'vendor_id']);

        return response()->json($invoices->map(fn($inv) => [
            'id'         => $inv->id,
            'invoice_no' => $inv->invoice_no,
            'vendor'     => $inv->vendor->name ?? '',
        ]));
    }

    public function getItemDetails($invoiceId, $itemId)
    {
        $item = PurchaseInvoiceItem::with(['product', 'measurementUnit'])
            ->where('purchase_invoice_id', $invoiceId)
            ->where('item_id', $itemId)
            ->first();

        if (!$item) {
            return response()->json(['error' => 'Item not found.'], 404);
        }

        return response()->json([
            'item_id'   => $item->item_id,
            'item_name' => $item->product->name ?? '',
            'quantity'  => $item->quantity,
            'unit_id'   => $item->unit,
            'unit_name' => $item->measurementUnit->name ?? '',
            'price'     => $item->price,
        ]);
    }

    public function getProductInvoices($productId)
    {
        try {
            $invoices = PurchaseInvoice::whereHas('items', fn($q) => $q->where('item_id', $productId))
                ->with(['items' => fn($q) => $q->where('item_id', $productId)])
                ->get();

            return response()->json($invoices->map(function ($inv) {
                $item = $inv->items->first();
                return [
                    'id'         => $inv->id,
                    'invoice_no' => $inv->invoice_no,
                    'number'     => $inv->invoice_no, // used by JS dropdown label
                    'rate'       => $item?->price ?? 0,
                ];
            }));

        } catch (\Exception $e) {
            Log::error('[Purchase] getProductInvoices failed: ' . $e->getMessage());
            return response()->json(['error' => 'Failed to load invoices'], 500);
        }
    }

    // ── Private helpers ───────────────────────────────────────────────

    private function saveItems(PurchaseInvoice $invoice, array $items): void
    {
        $productNames = Product::pluck('name', 'id');
        foreach ($items as $itemData) {
            if (empty($itemData['item_id'])) continue;
            $invoice->items()->create([
                'item_id'      => $itemData['item_id'],
                'variation_id' => $itemData['variation_id'] ?? null,
                'item_name'    => $productNames[$itemData['item_id']] ?? null,
                'quantity'     => $itemData['quantity']     ?? 0,
                'unit'         => $itemData['unit']         ?? null,
                'price'        => $itemData['price']        ?? 0,
                'remarks'      => $itemData['item_remarks'] ?? null,
            ]);
        }
    }

    private function saveAttachments(PurchaseInvoice $invoice, Request $request): void
    {
        if (!$request->hasFile('attachments')) return;
        foreach ($request->file('attachments') as $file) {
            $invoice->attachments()->create([
                'file_path'     => $file->store('purchase_invoices', 'public'),
                'original_name' => $file->getClientOriginalName(),
                'file_type'     => $file->getClientMimeType(),
            ]);
        }
    }

    /**
     * DR  Stock in Hand (104001)      ← goods received
     * DR  Conveyance Expense (502001) ← conveyance charges
     * DR  Labour Expense (502002)     ← labour charges
     * CR  Vendor                      ← net payable
     * CR  Purchase Discount (402001)  ← discount received
     */
    private function postPurchaseEntries(PurchaseInvoice $invoice): void
    {
        $itemsTotal = $invoice->items->sum(fn($i) => $i->quantity * $i->price);
        $conveyance = (float)($invoice->convance_charges ?? 0);
        $labour     = (float)($invoice->labour_charges   ?? 0);
        $discount   = (float)($invoice->bill_discount    ?? 0);

        $this->syncVoucherEntries(
            $invoice,
            'purchase',
            $invoice->invoice_date,
            [
                ['dr' => '104001', 'cr_id' => $invoice->vendor_id, 'amount' => $itemsTotal, 'remarks' => 'Goods received — ' . $invoice->invoice_no],
                ['dr' => '502001', 'cr_id' => $invoice->vendor_id, 'amount' => $conveyance,  'remarks' => 'Conveyance — ' . $invoice->invoice_no],
                ['dr' => '502002', 'cr_id' => $invoice->vendor_id, 'amount' => $labour,      'remarks' => 'Labour — ' . $invoice->invoice_no],
                ['dr_id' => $invoice->vendor_id, 'cr' => '402001', 'amount' => $discount,    'remarks' => 'Purchase discount — ' . $invoice->invoice_no],
            ]
        );

        Log::info('[Purchase] Accounting synced', [
            'invoice_no' => $invoice->invoice_no,
            'items'      => $itemsTotal,
            'conveyance' => $conveyance,
            'labour'     => $labour,
            'discount'   => $discount,
        ]);
    }
}